import "./globals.css";
import "normalize.css/normalize.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "../redux/StoreProvider";
import { Toaster } from "react-hot-toast";
import Header from "../components/Header/Header";
import styles from "./layout.module.css";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className={styles.app}>
            <Header />
            <main className={styles.main}>{children}</main>
            <Footer />
          </div>
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
