/* tslint:disable */
/* eslint-disable */
/**
 * nextjs-tsoa-be
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
} from './OrderItem';

/**
 * 
 * @export
 * @interface OrderRequest
 */
export interface OrderRequest {
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof OrderRequest
     */
    items: Array<OrderItem>;
}

/**
 * Check if a given object implements the OrderRequest interface.
 */
export function instanceOfOrderRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function OrderRequestFromJSON(json: any): OrderRequest {
    return OrderRequestFromJSONTyped(json, false);
}

export function OrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrderItemFromJSON)),
    };
}

export function OrderRequestToJSON(value?: OrderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(OrderItemToJSON)),
    };
}

